### ISSUE TITLE
SublimeLinter-contrib-errcheck not listed with installed packages

### ISSUE THREAD

**Issue by drussel** [alecthomas/SublimeLinter-contrib-errcheck#1]
Sublime Text 3, mac os. Just downloaded. Do I need to add something before it appears? Thanks.

**Comment by alecthomas** [comment]
I haven't submitted it to Package Control yet. Let me do that.

**Comment by alecthomas** [comment]
A quicker option might be to just clone it into your packages directory.

**Comment by alecthomas** [comment]
Actually, I will probably be deleting this linter in favour of [SublimeLinter-contrib-gometalinter](https://github.com/alecthomas/SublimeLinter-contrib-gometalinter). It is a much more pleasant experience.
